on:
  pull_request:
    branches:
      - main
name: Pull request workflow
jobs:
  validate_assetlists:
    name: Check validators list
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check Validators Nomination schema
        uses: snapcart/json-schema-validator@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          json_schema: ./schema.nominations.json
          json_path_pattern: nominations/cycle*/nominations.json$
